### ISSUE TITLE
registerOnCloseMethod() broken with newest patch

### ISSUE THREAD

**Issue by r4inX** [Servoy/ngdesktopui#2]
Hey Guys,

we found a new issue with the latest patch of ngdesktopui. (With the previous version it was working just fine)
Used Servoy-Version is 2023.12.2.3924

We are getting the following error:
```
Uncaught TypeError: this.callbackOnClose is not a function
http://192.168.168.1:8183/HVO2go/92060.090bf73099bcfe9b.js:1:1103726
TypeError: this.callbackOnClose is not a function
```

In our onSolutionOpen() we got the following:

```
if(isNGdesktop == 1 && !application.isInDeveloper()){
		plugins.ngdesktopui.registerOnCloseMethod(onCloseNG)
}
```

onCloseNG() looks like this:

 
```
function onCloseNG(){
	var lcTitel = "Exit"
	var lcMessage = "Do you really want to close the Solution?"
	var lcResponse = plugins.dialogs.showQuestionDialog(lcTitel,lcMessage,"No","Exit")

	if(lcResponse != "Exit"){
		return false
	}
	
	return true
} 
```

Can you please look this up? You can test this really easy if u just copy the two code-parts into a testsolution.
Thanks in advance!

-Vik

**Comment by jcompagner** [comment]
ah that was overlooked
this commit;
https://github.com/Servoy/ngdesktopui/commit/e28e8d4e0506927694986141224cf8117f5d1239

makes this release really only run on Servoy 2024.03 which will be releases this month.

**Comment by jcompagner** [comment]
you need to go to the previous version of all the plugins (and i guess ngdesktop itself)

And only move on when you are on 2024.03 

We will update the indexes so they don't show up for lower versions anymore
